export function generateEmailHtml(contactPersonName, recipientEmail, positionContact, institution, departm, purposeAccess, dataTitle, modifiedUrl, nameCustodian, surnameCustodian, emailCustodian) {
    const year = new Date().getFullYear();
    return  `
    <!DOCTYPE html>
    <html>
    <head>
    <style>
        .header {
        background-color: #4CAF50;
        color: white;
        padding: 10px;
        text-align: center;
        }
        .content {
        padding: 20px;
        font-size: 16px;
        }
        .footer {
        background-color: #f1f1f1;
        color: black;
        text-align: center;
        padding: 10px;
        }
    </style>
    </head>
    <body>
    <div class="header">
        <h3>Request to access data published on Ebrains</h3>
    </div>
    <div class="content">
        <p>Dear ${nameCustodian} ${surnameCustodian}, email: ${emailCustodian}</p>
        <p>We have received a data access request for the following human dataset published
         on EBRAINS: ${dataTitle}, ${modifiedUrl}.</p>
        <p>${positionContact}, ${contactPersonName} from the ${institution}, ${departm} would like to perform: "${purposeAccess}"</p>
        <p>Would you kindley get in touch with ${contactPersonName} by email: ${recipientEmail} 
        to discuss possible collaboration and access to your data?</p>
        <p>If you have any questions to the curation team, feel free to <a href="mailto:support@example.com">contact us</a>.</p>
    </div>
    <div class="footer">
        <p>&copy; ${year} Ebrains curation team</p>
    </div>
    </body>
    </html>
    `
};

//${modifiedUrl}
/*
const htmlContent = `
<p>This is an authomatic email  generated by the data curation team. </p>
Dear ${nameCustodian} ${surnameCustodian},
We have received a data access request for the following human dataset published on EBRAINS: ${modifiedUrl}.
We contacted you on this email ${emailCustodian}.
We have recieved a request from ${contactPersonName} with email: ${recipientEmail}.  
`;  */

/* <p>If you have any questions, feel free to <a href="mailto:support@example.com">contact us</a>.</p>  */